version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 8.1.0
    - 8.2.0
  - dependency-name: serverless
    versions:
    - 2.20.1
    - 2.21.1
    - 2.28.7
    - 2.30.3
    - 2.31.0
    - 2.35.0
  - dependency-name: fork-ts-checker-webpack-plugin
    versions:
    - 6.2.1
  - dependency-name: serverless-webpack
    versions:
    - 5.4.0
  - dependency-name: next
    versions:
    - 10.0.9
    - 10.1.3
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.0
    - 4.18.0
    - 4.19.0
  - dependency-name: aws-amplify
    versions:
    - 3.3.22
    - 3.3.25
  - dependency-name: ts-loader
    versions:
    - 8.0.18
  - dependency-name: "@aws-amplify/auth"
    versions:
    - 3.4.20
    - 3.4.28
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
  - dependency-name: webpack
    versions:
    - 5.17.0
    - 5.19.0
    - 5.20.0
    - 5.24.4
    - 5.25.1
  - dependency-name: antd
    versions:
    - 4.11.1
    - 4.13.1
    - 4.14.0
  - dependency-name: aws-sdk
    versions:
    - 2.858.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.32
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
  - dependency-name: eslint
    versions:
    - 7.18.0
