name: frontend

on:
  push:
    paths:
      - 'packages/frontend/**'
      - 'packages/types/**'
      - '.github/workflows/frontend.yml'
      - '.eslintrc.js'
      - 'package.json'

jobs:
  lint_test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_GITHUB_ACTIONS_USER }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_GITHUB_ACTIONS_USER }}
          aws-region: us-east-1

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: actions/checkout@v2

      - name: Setup Yarn Cache
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules

      - name: Yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Lint
        run: yarn workspace frontend lint

      - name: Run tests
        run: yarn workspace frontend test

  build:
    name: Build
    needs: [lint_test]
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_GITHUB_ACTIONS_USER }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_GITHUB_ACTIONS_USER }}
          aws-region: us-east-1

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: actions/checkout@v2

      - name: Setup Yarn Cache
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules

      - name: Yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Build
        run: yarn workspace frontend build

  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/master'
    needs: [lint_test, build]
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_GITHUB_ACTIONS_USER }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_GITHUB_ACTIONS_USER }}
          aws-region: us-east-1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: actions/checkout@v2

      - name: Setup Yarn Cache
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules

      - name: Yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: deploy
        run: yarn workspace frontend deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_GITHUB_ACTIONS_USER }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_GITHUB_ACTIONS_USER }}
